In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\priya sharma\appdata\roaming\jupyter\runtime\video_game_analysis\env\lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in c:\users\priya sharma\appdata\roaming\jupyter\runtime\video_game_analysis\env\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\priya sharma\appdata\roaming\jupyter\runtime\video_game_analysis\env\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\priya sharma\appdata\roaming\jupyter\runtime\video_game_analysis\env\lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in c:\users\priya sharma\appdata\roaming\jupyter\runtime\video_game_analysis\env\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
df1 = pd.read_csv("vgsales.csv")
df1

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [3]:
df1.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [4]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  str
 2   Platform      16598 non-null  str
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  str
 5   Publisher     16540 non-null  str
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), str(4)
memory usage: 1.4 MB

In [5]:
df1.isna().sum()

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

In [6]:
## Year

df1["Year"] = df1["Year"].fillna(df1["Year"].median())

## Publisher

df1["Publisher"] = df1["Publisher"].fillna("Unknown")

In [7]:
## Covert year to int dtype

df1["Year"] = df1["Year"].astype(int)

In [8]:
df1.isna().sum()

Rank            0
Name            0
Platform        0
Year            0
Genre           0
Publisher       0
NA_Sales        0
EU_Sales        0
JP_Sales        0
Other_Sales     0
Global_Sales    0
dtype: int64

In [9]:
df1.to_csv("clean_vgsales.csv", index=False, encoding="utf-8")

In [10]:
import pandas as pd
df = pd.read_csv("clean_games.csv")

In [11]:
import pandas as pd
df1 = pd.read_csv("clean_vgsales.csv")

## Merging both datasets

In [18]:
print("df.columns:", df.columns)
print("df1.columns:", df1.columns)

df.columns: Index(['title', 'release_date', 'team', 'rating', 'times_listed',
       'number_of_reviews', 'genres', 'summary', 'reviews', 'plays', 'playing',
       'backlogs', 'wishlist'],
      dtype='str')
df1.columns: Index(['Rank', 'Name', 'Platform', 'Year', 'Genre', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales'],
      dtype='str')

In [21]:
df.columns = df.columns.str.strip()
df1.columns = df1.columns.str.strip()

In [22]:
df.rename(columns={"title": "Name"}, inplace=True)

In [23]:
df["Name"] = df["Name"].str.lower().str.strip()
df1["Name"] = df1["Name"].str.lower().str.strip()

In [24]:
df2 = pd.merge(df, df1, on="Name", how="inner")

In [25]:
df2

,Name,release_date,team,rating,times_listed,number_of_reviews,genres,summary,reviews,plays,...,Rank,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,minecraft,"Nov 18, 2011",Mojang Studios,4.3,2300.0,2300.0,"Adventure, Simulator",Minecraft focuses on allowing the player to ex...,Minecraft is what you make of it. Unfortunatel...,33000.0,...,73,X360,2013,Misc,Microsoft Game Studios,5.58,2.83,0.02,0.77,9.20
1,minecraft,"Nov 18, 2011",Mojang Studios,4.3,2300.0,2300.0,"Adventure, Simulator",Minecraft focuses on allowing the player to ex...,Minecraft is what you make of it. Unfortunatel...,33000.0,...,169,PS3,2014,Misc,Sony Computer Entertainment,1.97,2.51,0.00,0.94,5.42
2,minecraft,"Nov 18, 2011",Mojang Studios,4.3,2300.0,2300.0,"Adventure, Simulator",Minecraft focuses on allowing the player to ex...,Minecraft is what you make of it. Unfortunatel...,33000.0,...,298,PS4,2014,Misc,Sony Computer Entertainment Europe,1.38,1.87,0.12,0.65,4.02
3,minecraft,"Nov 18, 2011",Mojang Studios,4.3,2300.0,2300.0,"Adventure, Simulator",Minecraft focuses on allowing the player to ex...,Minecraft is what you make of it. Unfortunatel...,33000.0,...,644,XOne,2014,Misc,Microsoft Game Studios,1.43,0.76,0.00,0.22,2.41
4,minecraft,"Nov 18, 2011",Mojang Studios,4.3,2300.0,2300.0,"Adventure, Simulator",Minecraft focuses on allowing the player to ex...,Minecraft is what you make of it. Unfortunatel...,33000.0,...,715,PSV,2014,Misc,Sony Computer Entertainment Europe,0.28,0.79,0.87,0.32,2.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1302,the lego movie videogame,"Feb 04, 2014","WB Games, TT Fusion",2.8,184.0,184.0,"Adventure, Puzzle",Join Emmet and an unlikely group of resistance...,"Legal, Pretty Average Lego Game But It Was My ...",1700.0,...,3030,PS4,2014,Action,Warner Bros. Interactive Entertainment,0.24,0.31,0.01,0.11,0.67
1303,the lego movie videogame,"Feb 04, 2014","WB Games, TT Fusion",2.8,184.0,184.0,"Adventure, Puzzle",Join Emmet and an unlikely group of resistance...,"Legal, Pretty Average Lego Game But It Was My ...",1700.0,...,3056,WiiU,2014,Action,Warner Bros. Interactive Entertainment,0.35,0.23,0.03,0.06,0.66
1304,the lego movie videogame,"Feb 04, 2014","WB Games, TT Fusion",2.8,184.0,184.0,"Adventure, Puzzle",Join Emmet and an unlikely group of resistance...,"Legal, Pretty Average Lego Game But It Was My ...",1700.0,...,3884,XOne,2014,Action,Warner Bros. Interactive Entertainment,0.34,0.13,0.00,0.04,0.51
1305,the lego movie videogame,"Feb 04, 2014","WB Games, TT Fusion",2.8,184.0,184.0,"Adventure, Puzzle",Join Emmet and an unlikely group of resistance...,"Legal, Pretty Average Lego Game But It Was My ...",1700.0,...,4734,PSV,2014,Action,Warner Bros. Interactive Entertainment,0.05,0.26,0.00,0.09,0.41
1306,the lego movie videogame,"Feb 04, 2014","WB Games, TT Fusion",2.8,184.0,184.0,"Adventure, Puzzle",Join Emmet and an unlikely group of resistance...,"Legal, Pretty Average Lego Game But It Was My ...",1700.0,...,12266,PC,2014,Action,Warner Bros. Interactive Entertainment,0.02,0.04,0.00,0.01,0.06

In [26]:
df2.head()

,Name,release_date,team,rating,times_listed,number_of_reviews,genres,summary,reviews,plays,...,Rank,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,minecraft,"Nov 18, 2011",Mojang Studios,4.3,2300.0,2300.0,"Adventure, Simulator",Minecraft focuses on allowing the player to ex...,Minecraft is what you make of it. Unfortunatel...,33000.0,...,73,X360,2013,Misc,Microsoft Game Studios,5.58,2.83,0.02,0.77,9.20
1,minecraft,"Nov 18, 2011",Mojang Studios,4.3,2300.0,2300.0,"Adventure, Simulator",Minecraft focuses on allowing the player to ex...,Minecraft is what you make of it. Unfortunatel...,33000.0,...,169,PS3,2014,Misc,Sony Computer Entertainment,1.97,2.51,0.00,0.94,5.42
2,minecraft,"Nov 18, 2011",Mojang Studios,4.3,2300.0,2300.0,"Adventure, Simulator",Minecraft focuses on allowing the player to ex...,Minecraft is what you make of it. Unfortunatel...,33000.0,...,298,PS4,2014,Misc,Sony Computer Entertainment Europe,1.38,1.87,0.12,0.65,4.02
3,minecraft,"Nov 18, 2011",Mojang Studios,4.3,2300.0,2300.0,"Adventure, Simulator",Minecraft focuses on allowing the player to ex...,Minecraft is what you make of it. Unfortunatel...,33000.0,...,644,XOne,2014,Misc,Microsoft Game Studios,1.43,0.76,0.00,0.22,2.41
4,minecraft,"Nov 18, 2011",Mojang Studios,4.3,2300.0,2300.0,"Adventure, Simulator",Minecraft focuses on allowing the player to ex...,Minecraft is what you make of it. Unfortunatel...,33000.0,...,715,PSV,2014,Misc,Sony Computer Entertainment Europe,0.28,0.79,0.87,0.32,2.25

In [27]:
df2.shape

(1307, 23)

In [28]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 1307 entries, 0 to 1306
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               1307 non-null   str
 1   release_date       1307 non-null   str
 2   team               1307 non-null   str
 3   rating             1307 non-null   float64
 4   times_listed       1307 non-null   float64
 5   number_of_reviews  1307 non-null   float64
 6   genres             1306 non-null   str
 7   summary            1307 non-null   str
 8   reviews            1307 non-null   str
 9   plays              1307 non-null   float64
 10  playing            1307 non-null   float64
 11  backlogs           1307 non-null   float64
 12  wishlist           1307 non-null   float64
 13  Rank               1307 non-null   int64
 14  Platform           1307 non-null   str
 15  Year               1307 non-null   int64
 16  Genre              1307 non-null   str
 17  Publisher          1307 non-null   str
 18  NA_Sales           1307 non-null   float64
 19  EU_Sales           1307 non-null   float64
 20  JP_Sales           1307 non-null   float64
 21  Other_Sales        1307 non-null   float64
 22  Global_Sales       1307 non-null   float64
dtypes: float64(12), int64(2), str(9)
memory usage: 235.0 KB

In [29]:
df2.isna().sum()

Name                 0
release_date         0
team                 0
rating               0
times_listed         0
number_of_reviews    0
genres               1
summary              0
reviews              0
plays                0
playing              0
backlogs             0
wishlist             0
Rank                 0
Platform             0
Year                 0
Genre                0
Publisher            0
NA_Sales             0
EU_Sales             0
JP_Sales             0
Other_Sales          0
Global_Sales         0
dtype: int64

In [31]:
df2["genres"] = df2["genres"].fillna("Unknown")

In [32]:
df2.isna().sum()

Name                 0
release_date         0
team                 0
rating               0
times_listed         0
number_of_reviews    0
genres               0
summary              0
reviews              0
plays                0
playing              0
backlogs             0
wishlist             0
Rank                 0
Platform             0
Year                 0
Genre                0
Publisher            0
NA_Sales             0
EU_Sales             0
JP_Sales             0
Other_Sales          0
Global_Sales         0
dtype: int64

In [33]:
df2.drop(columns=["id"], errors='ignore', inplace=True)

In [34]:
df2.to_csv("merged_dataset.csv", index=False, encoding="utf-8")